### ISSUE TITLE
Can it be used even without internet?

### ISSUE THREAD

**Issue by AsumiArkhe** [dgk3593/dl-model#4]
Sorry for ask,Is it possible to download  to a computer and use it? I mean, can it be used even without internet?
I don't know much about coding, I'm just a DL fan. I downloaded your code, but when I opened index, it was blank.T_T

BTW, I'm looking for all portrait /dragon image in 1024x1024 size as a pack. can you help me for that?
I'm sorry to bother you and my thanks are 120 percent.

**Comment by dgk3593** [comment]
For the portraits, I think you can go to archive-project in the discord server and ask there.

It’s possible to run the model viewer offline.
- First you need to install [git](https://git-scm.com/downloads) and [node.js](https://nodejs.org/en/download/) 
- Then go to the folder where you want to save everything (around 10 GB is needed), hold shift and right click on an open space, then choose Open in Terminal 
- Enter ```git clone https://github.com/dgk3593/dl-model.git``` and wait for it to finish
- Enter ```cd dl-model```
- Enter ```npm i``` and wait for it to finish
- Enter ```npm run dev``` and go to the address with your web browser
- Close the terminal when you're done

If you’ve already downloaded the code, you only need to install node.js, then open terminal in the ```dl-model``` folder, enter ```npm i``` and then ```npm run dev```

From the second time onward, you only need to open a terminal inside the ```dl-model``` folder, enter ```npm run dev```, and go to the address in your web browser.
