### ISSUE TITLE
It seems the page has something wrong?

### ISSUE THREAD

**Issue by InfinityEx** [dgk3593/dl-model#6]
Hi pal, Appreciative all of your work for dl model first.
But recently I found a problem about the online page(https://dgk3593.github.io/dl-model/#/), It seems something wrong with a javascript file was not found.

Here's message in chrome devtools console:
`GET https://dgk3593.github.io/dl-model/assets/_commonjsHelpers-35101cd5.js net::ERR_ABORTED 404` &nbsp;&nbsp;`dgk3593.github.io/:34 `

headers
`Request URL: https://dgk3593.github.io/dl-model/assets/_commonjsHelpers-35101cd5.js`
`Request Method: GET`
`Status Code: 404`

I found the file in your repository‘s gh-page branch, but it not found in the online page.
It's may cause by deployment delay time?  Or just my network problem?
I'm sorry to bother you, but I hope to receive your reply.

**Comment by dgk3593** [comment]
Looks like it's a CDN problem, I'll see if I can fix it

**Comment by InfinityEx** [comment]
Thanks for your reply at this late hour! ( It seems make no difference to resolve the problem later. It not in a hurry I means 😆

**Comment by dgk3593** [comment]
It’s fixed now
