### ISSUE TITLE
Notte's Fly animation wings not moving

### ISSUE THREAD

**Issue by cobaph** [dgk3593/dl-model#7]
Hi, I just noticed that Notte's wings aren't flapping during her Fly animation. Is there a way to re-enable this using the model viewer? Thanks!

**Comment by dgk3593** [comment]
The Fly animation is apparently more like gliding so it's originally like that I think. GNotte doesn't flap her wing moving forward either.

**Comment by cobaph** [comment]
I thought that was how it was too, but I was watching a video on a reddit post of the home screen and noticed she was flapping.

**Comment by dgk3593** [comment]
I see. Unfortunately, I don't have the original assets for that to check anymore so it'll be staying that way.
