### ISSUE TITLE
Shadows export with a green tint?

### ISSUE THREAD

**Issue by SoraRoxasVentus** [dgk3593/dl-model#8]
Not sure if this is just a me issue or a site issue but just in case I'll open a ticket here, but exported characters (both in .glb and .gltf) seem to have a green tint on their shadows when imported into blender
![image](https://github.com/dgk3593/dl-model/assets/86068232/bb9311d0-85d3-4047-b826-f0eb4a7f4dd5)

**Comment by dgk3593** [comment]
I think there’s some settings regarding texture that can fix that but I don’t remember exactly which one as I don’t have Blender installed atm
